version: '3.8'

services:
  nginx:
    image: nginx:latest
    # platform: linux/amd64
    restart: unless-stopped
    container_name: nginx1
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./config/nginx/:/etc/nginx
      - ./frizar_backend:/var/www/html
      - ./config/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
    depends_on:
      # - frontend
      - php-fpm
    networks:
      - app_network

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.front
    platform: linux/amd64
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network

  # mysql:
  #   image: mysql:8.0
  #   # platform: linux/amd64
  #   restart: unless-stopped
  #   container_name: mysql1
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: frizar
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: admin
  #   volumes:
  #     - ./db_data:/var/lib/mysql
  #     - ./init:/docker-entrypoint-initdb.d/
  #     - ./config/mysql:/etc/mysql/conf.d/
  #   networks:
  #     - app_network
  mariadb:
    image: mariadb:latest
    # platform: linux/amd64
    restart: unless-stopped
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frizar
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/
      - ./config/mysql:/etc/mysql/conf.d/
    networks:
      - app_network

  php-fpm:
    image: php:8.3-fpm
    platform: linux/amd64
    build:
      context: ./frizar_backend
      dockerfile: ../Dockerfile.backend
    restart: unless-stopped
    container_name: php-fpm
    volumes:
      - ./frizar_backend:/var/www/html
    networks:
      - app_network
    ports:
      - 9000:9000

networks:
  app_network:
    driver: bridge
