# Используем официальный образ PHP как базу
FROM php:8.2-fpm

# Устанавливаем необходимые пакеты и расширения PHP для 1С-Битрикс
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libzip-dev \
    unzip \
    curl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd mbstring zip opcache mysqli pdo_mysql 
