version: '3.8'

services:
  nginx:
    image: nginx:latest
    # platform: linux/amd64
    restart: unless-stopped
    container_name: nginx1
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./config/nginx/:/etc/nginx
      - ./frizar_backend:/var/www/html
      - ./config/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
    depends_on:
      # - frontend
      - php-fpm
    networks:
      - app_network

  mariadb:
    image: mariadb:latest
    # platform: linux/amd64
    restart: unless-stopped
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frizar
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/
      - ./config/mysql:/etc/mysql/conf.d/
    networks:
      - app_network

  php-fpm:
    image: php:8.3-fpm
    # platform: linux/amd64
    build:
      context: ./frizar_backend
      dockerfile: ../Dockerfile.backend
    restart: unless-stopped
    container_name: php-fpm
    volumes:
      - ./frizar_backend:/var/www/html
    networks:
      - app_network
    ports:
      - 9000:9000

  meilisearch:
    image: getmeili/meilisearch:latest # Используйте последнюю версию MeiliSearch
    # platform: linux/amd64
    environment:
      # MEILI_NO_MAINTENANCE: "true" # Отключить режим обслуживания (если необходимо)
      MEILI_MASTER_KEY: aSampleMasterKey
    volumes:
      - ./meili_data/:/data.ms # Хранение данных MeiliSearch
    ports:
      - 7700:7700 # Порт для доступа к MeiliSearch
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
