services:

  meilisearch:
    image: getmeili/meilisearch:v1.13
    container_name: meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: aSampleMasterKey  # Optional but recommended for production
    volumes:
      - ./meili_data:/meili_data
    ports:
      - 7700:7700
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
